-- Run this SQL in your Supabase SQL Editor to create the necessary table

create table public.sales_approvals (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  status text not null default 'pending',
  bill_no text null,
  bill_date timestamp with time zone null,
  customer_name text null,
  executive text null,
  total_amount numeric null,
  sale_data jsonb null,
  constraint sales_approvals_pkey primary key (id)
);

-- Optional: Enable RLS (Row Level Security) if you need it
-- alter table public.sales_approvals enable row level security;
-- create policy "Enable read access for all users" on public.sales_approvals for select using (true);
-- create policy "Enable insert for all users" on public.sales_approvals for insert with check (true);
-- create policy "Enable update for all users" on public.sales_approvals for update using (true);
